### ISSUE TITLE
I can't save password if I use WSL 

### ISSUE THREAD

**Issue by ciwomuli** [pustaczek/icie#17]

**Comment by pustaczek** [comment]
Password storage needs to use gnome-keyring in order to be secure, so you need to install it somehow. It's often present on Linux distros, but apparently not on WSL. In case you need to see the detailed error message, open Help > Developer Tools > Console.

PS: Also, I'm working on version 0.7 with Windows/Mac support so that should eliminate the need for WSL once it comes out :)

**Comment by ciwomuli** [comment]
Thank you,and I am looking forward for version 0.7.
