### ISSUE TITLE
Does not work if clang is not installed

### ISSUE THREAD

**Issue by mikaelmello** [pustaczek/icie#3]
That one was hard to find!

Most commands were breaking with an `entity not found` error and after digging in the code, I narrowed the error to the build function which called `clang`, a compiler I didn't have.

Perhaps the extension should try GCC and if even that fails, display a nice error message?

I'm sorry for just creating issues, unfortunately I don't know Rust at all to help with PRs!

By the way, now that I've got everything working, this is a very nice extension.

**Comment by pustaczek** [comment]
Sorry, forgot to add the error message during the 0.5 rewrite. I will probably disable implicit error conversion since the system messages look so bad...

As for the GCC fallback, it will be convenient for me to add along with Windows compilation support. There isn't anything blocking it now that some other changes should remove one linking bug, so I should add it in the next few days.

**Comment by mikaelmello** [comment]
Great, thanks for the quick responses!
