### ISSUE TITLE
Every time i tries to submit a solution , an error stating "MinGw not installed" is popped up.

### ISSUE THREAD

**Issue by dhnanj2** [pustaczek/icie#33]
Every time i tries to submit a solution , an error stating "MinGw not installed" is popped up.
Though my system has MinGw installled in it.

**Comment by pustaczek** [comment]
This message means the extension could not find MinGW, and it only looks in C:\MinGW and C:\MinGW\mingw32. Have you installed it following the [instructions], or in some other way? If you installed it somewhere else, you can set the "ICIE Windows MinGW Path" config option (<kbd>Ctrl</kbd><kbd>,</kbd> > Extensions > ICIE) to your C:\\...something...\MinGW directory.

If you don't know where your MinGW is installed, you can try uninstalling it and installing using the [instructions] so that the extension will be able to find it.  

[instructions]: https://github.com/pustaczek/icie/blob/master/docs/WINDOWS.md

**Comment by dhnanj2** [comment]
Issue Resolved.....Thanks !

**Comment by krsinghshubham** [comment]
> Issue Resolved.....Thanks !

bro.. how you resolved it ?

**Comment by dhnanj2** [comment]
I followed the following steps ...

This message means the extension could not find MinGW, and it only looks in
C:\MinGW and C:\MinGW\mingw32. Have you installed it following the
instructions <https://github.com/pustaczek/icie/blob/master/docs/WINDOWS.md>,
or in some other way? If you installed it somewhere else, you can set the
"ICIE Windows MinGW Path" config option (Ctrl, > Extensions > ICIE) to your
C:\...something...\MinGW directory.

If you don't know where your MinGW is installed, you can try uninstalling
it and installing using the instructions
<https://github.com/pustaczek/icie/blob/master/docs/WINDOWS.md> so that the
extension will be able to find it.

**Comment by krsinghshubham** [comment]
there is nothing new in this solution, didnt worked for me.
