### ISSUE TITLE
Sample test cases were not being fetched for Codeforces contests

### ISSUE THREAD

**Issue by xyf007** [pustaczek/icie#34]
Yesterday I used ``Alt + F9`` to participate in Educational Codeforces Round 89, it did show the time till it began. However, when the contest began, it did not fetch the test cases at all. And it did not create the folder of each problem, either. Though I tried many times, restarting VS Code and using ``Alt + F9``, ``Alt + F11``, it still did not work.

**Comment by pustaczek** [comment]
That contest seems to work now, so it's likely not Codeforces changing something. I also don't think this extension could fail to do something without displaying an error message. When it's doing something, it should also update the status bar - in the lower left corner of the screen, there will be a snowflake icon and a list of all currently active operations, like "Fetching contest" or "Compiling". Was there anything displayed there, or did it disappear without creating the folder? It's also possible that it was retrying the requests due to a bad Internet connection, could have that been the case?

**Comment by xyf007** [comment]
> That contest seems to work now, so it's likely not Codeforces changing something. I also don't think this extension could fail to do something without displaying an error message. When it's doing something, it should also update the status bar - in the lower left corner of the screen, there will be a snowflake icon and a list of all currently active operations, like "Fetching contest" or "Compiling". Was there anything displayed there, or did it disappear without creating the folder? It's also possible that it was retrying the requests due to a bad Internet connection or Codeforces slowing down, could have that been the case?

There was the icon, so I think maybe it was caused by a bad Internet connection. So I suggest using ``https://codeforces.ml`` instead of ``https://codeforces.com``

**Comment by pustaczek** [comment]
From what I can find, it's some kind of mirror site for Chinese users? Does it work faster than .com in China? If that's the case, I could add support for it.

**Comment by xyf007** [comment]
> From what I can find, it's some kind of mirror site for Chinese users? Does it work faster than .com in China? If that's the case, I could add support for it.

Yeah, and when having contests, we may prefer ``m1.codeforces.com``, ``m2.codeforces.com``, ``m3.codeforces.com``. They do not offer the standings, but they are the quickiest. So maybe it's a better choice to use them when fetching test cases from a running contest.
