### ISSUE TITLE
"MinGW not installed"  

### ISSUE THREAD

**Issue by krsinghshubham** [pustaczek/icie#40]
1.MInGW is installed and working fine with coderun extension and even i myself use mingw for default compilaton.
2. MInGW is installed using default settings, path is not changed and added to system paths.
3. did  a restallation of compiler too.
 HELP !

**Comment by pustaczek** [comment]
This message means the extension could not find MinGW, and it only looks in C:\MinGW and C:\MinGW\mingw32. Have you installed it following the [instructions], or in some other way? If you installed it somewhere else, you can set the "ICIE Windows MinGW Path" config option (<kbd>Ctrl</kbd><kbd>,</kbd> > Extensions > ICIE) to your C:\\...something...\MinGW directory.

If you don't know where your MinGW is installed, you can try uninstalling it and installing using the [instructions] so that the extension will be able to find it.  

[instructions]: https://github.com/pustaczek/icie/blob/master/docs/WINDOWS.md

**Comment by krsinghshubham** [comment]
i see you are replying to this issue of me and other simply by pasting paragraph. 
did you checked the details i posted ?
i already checked every recommend instructions.

**Comment by pustaczek** [comment]
Ah, right. The entire [MinGW detection code](https://github.com/pustaczek/icie/blob/0039f8a84b971f9a07d38d84b5d34444d65735e9/src/compile/clang.rs#L73-L93) is less than 20 lines long. Basically, it just checks `C:\MinGW\mingw32\bin\g++.exe`, `C:\MinGW\bin\g++.exe` (or if you have set the "Compile: Windows Mingw Path" in the config to e.g `D:\Unicorn`, it **only** checks `D:\Unicorn\bin\g++.exe`), and if they exist it considers MinGW installed. Do these files actually exist at these locations?

**Comment by krsinghshubham** [comment]
![ss-1 compilation path](https://user-images.githubusercontent.com/47324260/89107634-ff5cd400-d44f-11ea-8318-8665abc9291f.png)
![ss-2 compilation error](https://user-images.githubusercontent.com/47324260/89107653-2a472800-d450-11ea-9fb3-26afa6a4d7e1.png)


yes these paths now exist and i am getting this new error. also creating a new issue in view of that. Please help
