### ISSUE TITLE
Notification Sound (Feature Request)

### ISSUE THREAD

**Issue by krsinghshubham** [pustaczek/icie#46]
Can you please add a sound notification feature when all the test cases gets passed or failed, because sites like codechef only accepts one login at a time.

**Comment by pustaczek** [comment]
You mean that after pressing Alt+F12, and waiting for submit and tests on the site to run, there should be a sound? There should already be a notification displaying the test results (whether they passed or failed) in the lower right corner, can you see it?

![Screenshot from 2021-01-01 20-31-29](https://user-images.githubusercontent.com/28683906/103445112-62a59900-4c70-11eb-8a96-5b7618548b7e.png)

**Comment by krsinghshubham** [comment]
yeah the notification pops , but not sure if it will show when we already moved on to next question. 
Notification with a sound will be a cool additon.

**Comment by pustaczek** [comment]
No, the notification won't show after switching to another task with Alt+Backspace, due to VS Code completely resetting itself when switching directories. This is an unfortunate limitation of the current directory-per-task approach, and **I usually just wait for the results to come in before moving on to the next question**, because reading the statement would distract me in case I need to debug a rejected solution.

How fixable this is? You'd need to change a bit of stuff to save everything in one directory, and (more importantly) design and add some mechanism for specifying e.g. which task Alt+F12 should submit. That'd be a rather large change and nowadays I have other projects to work on, but if someone else tries to do it I'd be willing to help/review/merge it.

Regarding just adding a sound to the notification, VS Code doesn't have an API for this, presumably because a lot of people would consider extensions playing sounds irritating.

**Comment by krsinghshubham** [comment]
I use many extensions , which only runs on file on which the cursor resides( in cases when multiple files are opened under one directory) so I think defining the target of 
Alt+F12 would be easy but sadly I lack skills to implement this on my own :(. 
I just pray that you get some time to modify this in future.
Thanks for your work.
